app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/app.py
from flask import Flask
from flask_admin import Admin
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_sqlalchemy import SQLAlchemy

from .config import Configuration
from .model_view import *

app: Flask = Flask(__name__)
app.config.from_object(Configuration)
db: SQLAlchemy = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

from .model import *

# falk security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)
# flask admin
admin = Admin(app, 'FlaskApp', url='/',
              index_view=HomeAdminView(name='Admin'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

app/main.py
from .posts.blueprint import posts
from .view import *

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == "__main__":
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_security import login_required
from sqlalchemy import exc

from .forms import PostForm
from ..app import db
from ..model import Post, Tag

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['GET', 'POST'])
@login_required
def post_create():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except exc.SQLAlchemyError as e:
            print(e)

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/post_create.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def post_edit(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if request.method == 'POST':
        form: PostForm = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        try:
            db.session.commit()
        except exc.SQLAlchemyError as e:
            print(e)
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/post_edit.html', post=post, form=form)


@posts.route('/')
def index():
    search_word = request.args.get('search')
    raw_page: str = request.args.get('page')
    if raw_page and raw_page.isdigit():
        page: int = int(raw_page)
    else:
        page = 1

    if search_word:
        posts_objects = Post.query.filter(
            Post.title.ilike(f'%{search_word}%') |
            Post.body.ilike(f'%{search_word}%'))  # .all()
    else:
        posts_objects = Post.query.order_by(Post.date_created.desc())

    pages = posts_objects.paginate(page=page, per_page=3)

    return render_template(
        'posts/post_index.html', posts=posts_objects, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}
Create new post
{% endblock %}

{% block content_title %}
New post
{% endblock %}

{% block content %}
<div class="col-md-8">
    <form action="{{ url_for('posts.post_create') }}" method="POST">
        {% for field in form %}
        <div class="form-group">
            {{ field.label(class='control-label') }}
            {{ field(class='form-control') }}
        </div>
        {% endfor %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button type="submit" class="btn btn-success">Create</button>
        </div>

    </form>
</div>

{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content_title %}
{{ post.title }}
{% endblock %}

{% block content %}
{{ post.body }}
{% endblock %}

app/posts/templates/posts/post_edit.html
{% extends 'base.html' %}

{% block title %}
Edit new post
{% endblock %}

{% block content_title %}
Edit post
{% endblock %}

{% block content %}
<div class="col-md-8">
    <form action="{{ url_for('posts.post_edit', slug=post.slug) }}" method="POST">
        {% for field in form %}
        <div class="form-group">
            {{ field.label(class='control-label') }}
            {{ field(class='form-control') }}
        </div>
        {% endfor %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button type="submit" class="btn btn-success">Update</button>
        </div>

    </form>
</div>

{% endblock %}

app/posts/templates/posts/post_index.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock %}

{% block content_title %}
Posts
{% endblock %}

{% block content %}
Blueprint Content
{% for post in pages.items %}
<div class="card border-info mb-3">
    <div class="card-header">
        {{ post.date_created }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.body[:50] }}</p>

        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"
           class="btn btn-outline-info">Read</a>
    </div>
    <div class="card-footer">
        {% for tag in post.tags %}
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"
           class="btn btn-link btn-sm">{{ tag.name }}</a>
        {% endfor %}
    </div>
</div>
{% endfor %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
            <a class="page-link" href="./?page={{ pages.prev_num }}"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for page in pages.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
        {% if page %}
            {% if page != pages.page %}
                <li class="page-item"><a class="page-link" href="./?page={{ page }}">{{
                page }}</a></li>
            {% else %}
                <li class="page-item active"><a class="page-link"
                                        href="./?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% else %}
            <span class=ellipsis>…</span>
        {% endif %}
        {% endfor %}

        <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
            <a class="page-link" href="./?page={{ pages.next_num }}"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
{{ tag.name }} posts
{% endblock %}

{% block content_title %}
 Posts for {{ tag.name }} tag:
{% endblock %}

{% block content %}
{% for post in posts %}
<div>
    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"
           class="btn btn-outline-info">{{ post.title }}</a>
</div>

{% endfor %}
{{ tag.name }}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %} | Flask app
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-pill border border-danger">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index') }}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{{ url_for('posts.index') }}">Blogs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{{ url_for('posts.post_create') }}">Create new
                        post</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another
                            action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else
                            here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    {% if current_user.has_role('admin') %}
                    <a class="nav-link" href="/admin" tabindex="-1"
                       aria-disabled="true">Admin</a>
                    {% endif %}
                </li>
            </ul>
            <form class="d-flex" method="GET">
                <input class="form-control me-2" type="search"
                       placeholder="Search" aria-label="Search"
                       name="search"
                       value="{{ request.args.get('search', '') }}">
                <button class="btn btn-outline-success" type="submit">Search
                </button>
            </form>
        </div>
    </div>
</nav>

<div class="container">
    <div class="col">
        <h2>
            {% block content_title %}

            {% endblock %}
        </h2>
        {% block content %}

        {% endblock %}
    </div>
</div>


</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
Bla bla bla title
{% endblock %}

{% block content_title %}
bla content_title
{% endblock %}

{% block content %}
Some content bla bla bal
{% endblock %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block content_title %}
<div class="col-md-6 offset-md-3">
<h1>{{ _('Login') }}</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-md-6 offset-md-3">
    {% from "security/_macros.html" import render_field_with_errors,
    render_field %}
    {% include "security/_messages.html" %}

    <form action="{{ url_for_security('login') }}" method="POST"
          name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        {{ render_field_with_errors(login_user_form.email,
        class='form-control') }}
        {{ render_field_with_errors(login_user_form.password,
        class='form-control') }}
        {{ render_field_with_errors(login_user_form.remember) }}
        {{ render_field(login_user_form.next) }}
        {{ render_field(login_user_form.submit, class="btn btn-success") }}
    </form>
    {% include "security/_menu.html" %}
</div>
{% endblock %}